PATH_DATA_FILES = "/Users/quentin/Computer/DataSet/Music/MIDI/essen/**/**/*.krn"

SEQUENCE_LENGTH = 15
NUMBER_EPOCHS = 500
BATCH_SIZE = 128
GENERATION_LENGTH = 100

NUMBER_GENERATED_STATES = 10000
REAL_NB_NOTES = 52
